# Generated by Django 3.2.6 on 2022-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='get_mails',
            field=models.BooleanField(default=False),
        ),
    ]
