# Generated by Django 3.2.6 on 2022-01-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('voice_en', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_jp', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('other_names', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('num_of_eps', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('studio', models.CharField(blank=True, max_length=150, null=True)),
                ('directors', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('popularity_rank', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('episode_summary', models.JSONField(blank=True, null=True)),
                ('poster_image', models.URLField(blank=True, max_length=255, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=255, null=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='anime', to='animu.Character')),
                ('genres', models.ManyToManyField(blank=True, related_name='animes', to='animu.Genre')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
    ]
